### ISSUE TITLE
Investigate docker-related issue with new storage approach

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#413] opened 2021-07-15 18:32 UTC
When attempting to run the processing scripts from the TF docker utilizing a fresh install, the extraction process fails for each video due to disallowed storage actions OSError: [Errno 18] Invalid cross-device link: 
```
7%| | 19/292 [00:26<04:49,  1.06s/video, video=1f4f6311bb4acc0bc72e4a915a32093Error processing file:data/beckham_70_yard_goal/1f4f6311bb4acc0bc72e4a915a32093a7a85741c.flv
Traceback (most recent call last):
  File "/project/winnow/feature_extraction/extraction_routine.py", line 82, in feature_extraction_videos
    on_extracted(video_file_path, video_tensor, features)
  File "/project/winnow/pipeline/extract_frame_level_features.py", line 39, in save_features
    pipeline.repr_storage.frame_level.write(key, frames_features)
  File "/project/winnow/storage/simple_repr_storage.py", line 91, in write
    self._metadata_loader.dump(metadata, metadata_file)
  File "/anaconda/envs/winnow/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/project/winnow/storage/atomic_file.py", line 69, in atomic_file_open
    yield file
  File "/anaconda/envs/winnow/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/project/winnow/storage/atomic_file.py", line 43, in atomic_file_path
    os.rename(temporary_path, destination_path)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpk05wx84z' -> '/project/data/representations/frame_level/beckham_70_yard_goal/1f4f6311bb4acc0bc72e4a915a32093a7a85741c.flv_7b0393854fe9fd6602eaf8af2fdcaadac073a3193245fe033eec78bc8376b1d0_vgg_features.npy'
```

**Comment by stepan-anokhin** [comment] 2021-07-19 07:34
Root cause is the final step of atomic file write (moving the written temporary file to the destination path) which is implemented using `os.rename()` method. 

According to the `os.rename()` documentation: 

> The operation may fail on some Unix flavors if src and dst are on different filesystems. If successful, the renaming will be an atomic operation (this is a POSIX requirement).

The problem could be resolved by using `shutil.move()` method instead. According to the `shutil.move()` documentation: 

> If the destination is on the current filesystem, then os.rename() is used. Otherwise, src is copied to dst using copy_function and then removed.

**Closed** 2021-09-30 18:09 UTC
Labels: bug, storage
