### ISSUE TITLE
Investigate repr migration error

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#304] opened 2021-02-23 17:58 UTC
Another error happened after running the above command:

(winnow) tf-docker /project > just migrate reprs
Migrating to lmdb storage:
        src=/project/data/representations/frames
        dst=/project/data/representations/frames
Migrating to lmdb storage:
        src=/project/data/representations/frame_level
        dst=/project/data/representations/frame_level
Traceback (most recent call last):
  File "/anaconda/envs/winnow/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda/envs/winnow/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/project/cli/cli/main.py", line 6, in <module>
    fire.Fire(RootCli, name="just")
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/anaconda/envs/winnow/lib/python3.6/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/project/cli/cli/handlers/migration.py", line 18, in reprs
    path_to_lmdb.migrate_all_inplace(clean_source=clean)
  File "/project/winnow/storage/repr_migrate.py", line 63, in migrate_all_inplace
    representations=representations,
  File "/project/winnow/storage/repr_migrate.py", line 53, in migrate_all
    clean_source=clean_source,
  File "/project/winnow/storage/repr_migrate.py", line 36, in migrate_single_storage
    lmdb_storage.write(key=ReprKey(path=path, hash=sha256, tag=config_tag), value=repr_value)
  File "/project/winnow/storage/lmdb_repr_storage.py", line 105, in write
    self._write_metadata(key, txn)
lmdb.Error: mdb_txn_commit: Input/output error

**Comment by johnhbenetech** [comment] 2021-02-24 16:31
this seems to be an issue with s3fs incompatibility with LMDB

**Comment by stepan-anokhin** [comment] 2021-02-26 13:15
The problem is caused by the incompatibility between LMDB and s3fs.

Once #306 is merged there will be two options to resolve the problem:

### Solution #1. Use local file system to store extracted features. 

Change the following option in `config.yaml`:
```yaml
repr:
  directory: <repr-storage-path>
```
where `<repr-storage-path>` should point to the folder outside of the `s3fs`. 

### Solution #2. Use simple feature storage

Make sure `config.yaml` contains the following lines:
```yaml
repr:
  directory: <repr-storage-path>
  storage_type: simple
```
where `<repr-storage-path>` should be left unchanged (it is `data/` by default) and `storage_type: simple` should be added.

**Closed** 2021-04-01 20:25 UTC
